workflows:
  default-workflow:
    name: Charles Autos Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          echo "Listing ios/Flutter directory for debugging:"
          ls ios/Flutter
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release --no-pub
      - name: Build iOS IPA (Unsigned)
        script: |
          flutter build ipa --release --no-codesign --no-pub
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - build/ios/iphoneos/*.ipa
