workflows:
  default-workflow:
    name: Charles Autos Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          cd charles_autos_frontend
          flutter pub get
      - name: Build Android App Bundle
        script: |
          cd charles_autos_frontend
          flutter build appbundle --release --no-pub
      - name: Build iOS IPA (Unsigned)
        script: |
          cd charles_autos_frontend
          flutter build ipa --release --no-codesign --no-pub
    artifacts:
      - charles_autos_frontend/build/**/outputs/**/*.aab
      - charles_autos_frontend/build/**/outputs/**/*.apk
      - charles_autos_frontend/build/ios/iphoneos/*.ipa
